#本地
#server:
#  port: ":8080"
#ipPort: "192.168.201.101:7751"
#dataDir: "D:\\helin\\helin\\data"
#serverIpAdr: "/api-obj/obj/"
#测试服务器
#server:
#  port: ":8080"
#dataDir: "C:\\helin\\data"
#serverIpAdr: "http://81.68.165.103:8080/obj/"
#serverIpAdr: "/api-obj/obj/"
#生产服务器
server:
  port: ":8080"
ipPort: "192.168.201.101:7751"
dataDir: "D:\\helin\\data"
serverIpAdr: "/api-obj/obj/"

